### ISSUE TITLE
Bootstrap Input Group Add On right border color

### ISSUE THREAD

**Issue by hamidfzm** [morteza/bootstrap-rtl#126]
<img width="623" alt="screen shot 1396-02-07 at 9 39 33 pm" src="https://cloud.githubusercontent.com/assets/5591800/25495393/2eaf44dc-2b92-11e7-8403-8cbce80a9ce7.png">

In bootstrap rtl no right border color is defined for input group addon.  Here is the current code:

```css
.input-group-addon:first-child {
    border-left: 0;
    border-right: 1px solid;
}
```

If you change it into something like this probably solve the problem for bootstrap current theme. But for other themes I don't think so...

```css
.input-group-addon:first-child {
    border-left: 0;
    border-right: 1px solid #ccc;
}
```

<img width="604" alt="screen shot 1396-02-07 at 9 44 57 pm" src="https://cloud.githubusercontent.com/assets/5591800/25495556/c9e272ee-2b92-11e7-82c0-016b80c0545d.png">
